services:
 bot:
   build: .
   environment:
     - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
     - DATABASE_URL=postgresql+psycopg://user:password@db:5432/monitor
     - ADMIN_USERNAME=${ADMIN_USERNAME}
     - ADMIN_PASSWORD=${ADMIN_PASSWORD}
   depends_on:
     - db
   volumes:
     - .:/app
   command: >
     sh -c "python -m init_db && python -m bot.bot"

 web:
   build: .
   environment:
     - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
     - DATABASE_URL=postgresql+psycopg://user:password@db:5432/monitor
     - ADMIN_USERNAME=${ADMIN_USERNAME}
     - ADMIN_PASSWORD=${ADMIN_PASSWORD}
   depends_on:
     - db
   ports:
     - "8000:8000"
   volumes:
     - .:/app
   command: uvicorn web.main:app --host 0.0.0.0 --port 8000

 db:
   image: postgres:15
   environment:
     - POSTGRES_USER=user
     - POSTGRES_PASSWORD=password
     - POSTGRES_DB=monitor
     - TZ=Europe/Moscow
   volumes:
     - postgres_data:/var/lib/postgresql/data

volumes:
 postgres_data: